version: '2.1'

services: 
  app:
    build: ./
    ports:
      - "4000:4000"
    volumes: 
      - ./:/app
      #- /app/node_modules
    restart: on-failure 
    links: 
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: '123@34578.as'
      PORT: '4000'
    entrypoint: ./docker-entrypoint.sh

  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: '123@34578.as'
      MYSQL_DATABASE: 'ads'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d