# Generated by Django 3.2.6 on 2021-08-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_votes2_choice_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='votes2',
        ),
    ]
